### ISSUE TITLE
[Bug] Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by PikeNote** [EricZimmerman/Lnk#10]
There is a bug when using Lnk to process [this](https://github.com/EricZimmerman/Lnk/files/10405373/RuneChanger.zip) shortcut. When using this in my application, it returns
```
System.OverflowException
  HResult=0x80131516
  Message=Array dimensions exceeded supported range.
  Source=Lnk
  StackTrace:
   at Lnk.ShellItems.ShellBag0X31..ctor(Byte[] rawBytes)
   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)
   at Lnk.Lnk.LoadFile(String lnkFile)
...
```
I am currently on Windows 11 Home Version 10.0.22621 Build 22621

Running a test on it via the project files, it returns
![image](https://user-images.githubusercontent.com/56088716/212164162-69a475b9-cd4e-45e7-a0b6-ecccc568fca9.png)

**Comment by EricZimmerman** [comment]
this is fixed. definitely an edge case

```
Source file: C:\temp\RuneChanger.download
Source created: 7/6/2023 8:19:26 PM +00:00
Source modified: 7/6/2023 7:51:51 PM +00:00
Source accessed: 7/6/2023 9:16:28 PM +00:00

--- Header ---
  File size: 0
  Flags: HasTargetIdList, HasLinkInfo, HasName, HasRelativePath, HasWorkingDir, HasIconLocation, IsUnicode
  File attributes: 0
  Icon index: 0
  Show window: SwNormal (Activates and displays the window. The window is restored to its original size and position if the window is minimized or maximized.)
  Target created: 1/16/1601 9:44:19 AM +00:00
  Target modified: 1/16/1601 9:44:19 AM +00:00
  Target accessed: 1/16/1601 9:44:19 AM +00:00

--- Target ID information ---
>>Type: Root folder: GUID, Value: My Computer

>>Type: Drive letter, Value: C:

>>Type: Directory, Value: Users

Short name: Users

>>Type: Directory, Value: xxx

Short name: xxx

>>Type: Directory, Value: OneDrive

Short name: OneDrive

>>Type: Directory, Value: Documents

Short name: Documents

>>Type: Directory, Value: RuneChanger-1.15.0

Short name: RuneChanger-1.15.0

>>Short name: open.bat

Type: File, Value: open.bat


--- Link information ---
Location flags: VolumeIdAndLocalBasePath

Volume information
Drive type: DriveFixed
Serial number: 00000000
Label: (No label)
Local path: C:\Users\xxx\OneDrive\Documents\RuneChanger-1.15.0\open.bat
Name: RuneChanger
Relative Path: ..\Documents\RuneChanger-1.15.0\open.bat
Working Directory: C:\Users\xxx\OneDrive\Documents\RuneChanger-1.15.0
Icon Location: C:\Users\xxx\OneDrive\Documents\RuneChanger-1.15.0\icon.ico

```

Will be in the next release
