### ISSUE TITLE
Exception loading shortcut file

### ISSUE THREAD

**Issue by dfev77** [EricZimmerman/Lnk#4]
Receiving this exception when trying to load an lnk file.
The shortcuts are created by an installer, and the error only occurs on a remote computer (code is part of some tests).

I've copied the shortcut file here: https://drive.google.com/file/d/1DlCeylZZPW8FOoes6mG-1RgnHBPobJW4/view

System.ArgumentException : Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at ExtensionBlocks.PropertyStore..ctor(Byte[] rawBytes)
   at ExtensionBlocks.Beef0026..ctor(Byte[] rawBytes)
   at ExtensionBlocks.Utils.GetExtensionBlockFromBytes(Int64 signature, Byte[] rawBytes)
   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes) in D:\Code\Lnk\Lnk\ShellItems\ShellBag0x1f.cs:line 66
   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile) in D:\Code\Lnk\Lnk\LnkFile.cs:line 110
   at Lnk.Lnk.LoadFile(String lnkFile) in D:\Code\Lnk\Lnk\Lnk.cs:line 17

**Comment by EricZimmerman** [comment]
Please send me the lnk file

**Comment by EricZimmerman** [comment]
ok, i tweaked the extension block nuget package to make sure theres enough data. its uploading/validating now.

lnk nuget updated to 1.2.0.2 with the dependency fix. 

try that and let me know how it goes

**Comment by dfev77** [comment]
Thank you for you prompt reply!
Yes it works with 1.2.0.2 (though I don't understand why, cause I see no differences in the code) :)

Thanks again!

**Comment by EricZimmerman** [comment]
Different project. Look at the extension lock repo
